exports.fetchEntry = async () => {
	return [
  [
    {"id": 1, "name": "adobo", "image-path": "image/adobo", "type": "pork"},
    {"id": 2, "name": "sinigang", "image-path": "image/sinigang", "type": "pork"},
    {"id": 3, "name": "kare-kare", "image-path": "image/kare-kare", "type": "beef"},
    {"id": 4, "name": "menudo", "image-path": "image/menudo", "type": "pork"},
    {"id": 5, "name": "afritada", "image-path": "image/afritada", "type": "chicken"},
    {"id": 6, "name": "tinola", "image-path": "image/tinola", "type": "chicken"},
    {"id": 7, "name": "kaldereta", "image-path": "image/kaldereta", "type": "beef"},
    {"id": 8, "name": "nilaga", "image-path": "image/nilaga", "type": "beef"},
    {"id": 9, "name": "laing", "image-path": "image/laing", "type": "vegetable"},
    {"id": 10, "name": "pakbet", "image-path": "image/pakbet", "type": "vegetable"},
    {"id": 11, "name": "bicol express", "image-path": "image/bicol_express", "type": "pork"},
    {"id": 12, "name": "pork steak", "image-path": "image/pork_steak", "type": "pork"},
    {"id": 13, "name": "chicken inasal", "image-path": "image/chicken_inasal", "type": "chicken"},
    {"id": 14, "name": "lechon kawali", "image-path": "image/lechon_kawali", "type": "pork"},
    {"id": 15, "name": "crispy pata", "image-path": "image/crispy_pata", "type": "pork"},
    {"id": 16, "name": "ginisang monggo", "image-path": "image/ginisang_monggo", "type": "vegetable"},
    {"id": 17, "name": "tortang talong", "image-path": "image/tortang_talong", "type": "vegetable"},
    {"id": 18, "name": "pinapaitan", "image-path": "image/pinapaitan", "type": "beef"},
    {"id": 19, "name": "igado", "image-path": "image/igado", "type": "pork"},
    {"id": 20, "name": "dinuguan", "image-path": "image/dinuguan", "type": "pork"},
    {"id": 21, "name": "longganisa", "image-path": "image/longganisa", "type": "pork"},
    {"id": 22, "name": "sisig", "image-path": "image/sisig", "type": "pork"},
    {"id": 23, "name": "tokwa’t baboy", "image-path": "image/tokwat_baboy", "type": "pork"},
    {"id": 24, "name": "batchoy", "image-path": "image/batchoy", "type": "pork"},
    {"id": 25, "name": "mami", "image-path": "image/mami", "type": "beef"},
    {"id": 26, "name": "pancit canton", "image-path": "image/pancit_canton", "type": "noodle"},
    {"id": 27, "name": "pancit bihon", "image-path": "image/pancit_bihon", "type": "noodle"},
    {"id": 28, "name": "pancit palabok", "image-path": "image/pancit_palabok", "type": "noodle"},
    {"id": 29, "name": "lumpiang shanghai", "image-path": "image/lumpiang_shanghai", "type": "pork"},
    {"id": 30, "name": "lumpiang sariwa", "image-path": "image/lumpiang_sariwa", "type": "vegetable"},
    {"id": 31, "name": "ukoy", "image-path": "image/ukoy", "type": "seafood"},
    {"id": 32, "name": "ginataang kalabasa", "image-path": "image/ginataang_kalabasa", "type": "vegetable"},
    {"id": 33, "name": "ginataang hipon", "image-path": "image/ginataang_hipon", "type": "seafood"},
    {"id": 34, "name": "tinolang tahong", "image-path": "image/tinolang_tahong", "type": "seafood"},
    {"id": 35, "name": "grilled bangus", "image-path": "image/grilled_bangus", "type": "seafood"},
    {"id": 36, "name": "inihaw na pusit", "image-path": "image/inihaw_na_pusit", "type": "seafood"},
    {"id": 37, "name": "rellenong bangus", "image-path": "image/rellenong_bangus", "type": "seafood"},
    {"id": 38, "name": "daing na bangus", "image-path": "image/daing_na_bangus", "type": "seafood"},
    {"id": 39, "name": "tinapa", "image-path": "image/tinapa", "type": "seafood"},
    {"id": 40, "name": "ginisang ampalaya", "image-path": "image/ginisang_ampalaya", "type": "vegetable"},
    {"id": 41, "name": "chopseuy", "image-path": "image/chopseuy", "type": "vegetable"},
    {"id": 42, "name": "ensaladang talong", "image-path": "image/ensaladang_talong", "type": "vegetable"},
    {"id": 43, "name": "bulalo", "image-path": "image/bulalo", "type": "beef"},
    {"id": 44, "name": "pochero", "image-path": "image/pochero", "type": "beef"},
    {"id": 45, "name": "arroz caldo", "image-path": "image/arroz_caldo", "type": "chicken"},
    {"id": 46, "name": "lugaw", "image-path": "image/lugaw", "type": "rice"},
    {"id": 47, "name": "goto", "image-path": "image/goto", "type": "beef"},
    {"id": 48, "name": "tapsilog", "image-path": "image/tapsilog", "type": "beef"},
    {"id": 49, "name": "tocilog", "image-path": "image/tocilog", "type": "pork"},
    {"id": 50, "name": "longsilog", "image-path": "image/longsilog", "type": "pork"},
    
  ]
]

};
